language: node_js
node_js:
- 10.16.3
script:
- echo "Deploying!"
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --token $FIREBASE_TOKEN
env:
  global:
    secure: D8eXE+Ji/05xvlSjYsh0T06+rQ7H9w7quKHuPsntgZNb95p+jqlWB/f9ivKXxqhv6AAIm5pj6ouJfBDSun/GeYt+75km9zP+xtXOf/0LUXelH0xR3Jf5GPdHtsAO5WlnBdaVRo2frqDfqFwK1m3GAZnn3dQKKkBt5U0Z6mYsqxMyjK8HKg+Fd/xlrQTrCsMiOD8KMGfq70loMqJvO0qWdzxjIOiXb3Nau+7cYb5/khhdENotI7rp0Rrhoz/QkRrBpmxaah4XzPQx8UNrjIk1sHf+yDqL7QeT8mGbC4oeC/JlgOzDEm9DKWp2tAUOTvAcj6n4jF80+N7WjuwW36FiuHNvBpsaFlbVHQIZmRvZlLWVgLlM8Xt58PoYTUrHzcOxxj1WeMA1FFkfG0NIrQCpyD0ZVytVbtp7Nt0grWPGjMTkjIDaPvOC6vSQaSTe5546MhCmSH7TkCQHzbbn0eFbia0OTmBVY9/Yz6VaDXtO0wtKsjUvHT4cQMfW3gBE5uPQihf7f6YrvF9gsiwh6jY0hNy1n7NNXB7yYfEMOzEZfD9F8KTwToQCZK/IM9okoTQh+WGBijssVeMFeA461YfUwIXEaSXsoL2t8l/5bc6+nHfRNei9Zw6W/1pOQ88d5Zz3WAa/mP8yDvGRyPni1MGDi+1mSZVnXmvj3kR4A1KAUms=
